spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fintech?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 5959
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: fast-campus.com.fintech_2024_secret_key
  token.expired-time-ms: 86400000