spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fintech_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: tester
    password: Imtestpassword!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret-key: fast-campus.com.fintech_2024_secret_key
  token.expired-time-ms: 86400000
oauth2:
  kakao:
    grant-type: authorization_code
    client-id: unknownIdkfsjdifjoiesfjoiejsiofjesiofjioes
    client-secret: unknownIdkfsjdifjoiesfjoiejsiofjesiofjioessd
    redirect-uri: http://localhost:8080/api/login/kakao
    token-url: https://kauth.kakao.com
    user-info-url: https://kapi.kakao.com
    token-url-type: /oauth/token
    user-info-url-type: /v2/user/me

#logging:
#  level:
#    org.springframework.web.servlet.resource.ResourceHttpRequestHandler: ERROR
#jasypt:
#  encryptor:
#    password: ${jasypt-password}

